name: boundary_mover
seed: null

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

network_pkl: ${work_dir}/runs/00000-bedroom_256_train_mixed-mirror-stylegan2-kimg15000/network-snapshot-015000.pkl
classifier_pkl: ${work_dir}/outputs/bedroom_256_classification/2022-03-21-16-38-14/ckpts/vgg19_bn-epoch11-step9999.ckpt
measurer_pkl: ${work_dir}/outputs/bedroom_256_similarity/2022-03-22-16-31-15/ckpts/regnet_x_8gf-epoch23-step9999.ckpt
autoencoder_f2e_pkl: ${work_dir}/outputs/bedroom_256_autoencoder_f2e/2022-05-09-08-29-41/ckpts/autoencoder-epoch114-step49335.ckpt
target_cls: 1
source_fname: ""
source_dir: /home/ubuntu/bedroom_256_train/
random_source_fname: False
num_steps: 500
save_video: True

mode: "random_seed"
outdir: ${work_dir}/results/boundary_mover/random_img/classifier_only
reference_dir: ${work_dir}/results/boundary_mover/random_img/classifier_only
disable_networks: ["measurer_pkl", "autoencoder_f2e_pkl"]
use_ssim: False
use_deeplabv3: False
use_kmeans: False

hydra:
  run:
    dir: ./outputs/${name}/${now:%Y-%m-%d-%H-%M-%S}
